### PR TITLE
Upgrade to xenial

### PR DESCRIPTION
**Pull request by eisnerd**
You may want to bring this in to a different branch, if at all. I just thought I'd save you a few minutes if you wanted this, since I've been building them anyway.

### CODE REVIEW

**Comment by kindermoumoute** [comment]
This is also required for https://github.com/sameersbn/docker-bind/issues/16

**Comment by sameersbn** [comment]
Thanks for the PR. Will merge this PR.

**Comment by DoubleMalt** [comment]
I'm currently trying to get the docker-gitlab image to build for armhf, and an upgrade here would make everything much easier.

**Comment by DoubleMalt** [comment]
@sameersbn is there anything I can do to help getting this merged? Maybe even in a separate branch for now, then it could be built as a separate tag and the dependent images could be moved over step by step.

**Pull request merged**
